[package]
name = "kura-query"
version = "0.1.0"
edition = "2021"

[dependencies]
kurasql = { path = "../kurasql" }
datafusion = { version = "54.1", default-features = false, features = ["sql", "string_expressions", "unicode_expressions", "recursive_protection"] }
serde_json = "1"
sqlparser = { version = "0.41", features = ["visitor"] }
tokio = { version = "1", features = ["time"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
